stages:
    - dev

dev:
    stage: dev
    only:
        - branches
    image: docker/compose:2.13.0
    services:
        - docker:20.10.21-dind
    before_script:
        - apk add --no-cache make
    script:
        - make init
    tags:
        - runner_1