stages:
    - dev

dev:
    image: docker/compose:1.26.0
    services:
        - docker:19.03-dind
    stage: dev
    script:
        - docker -v
        - docker-compose -v
    tags:
        - runner_1