stages:
    - dev

variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_HOST: tcp://docker:2376

dev:
    stage: dev
    only:
        - branches
    image: docker/compose:latest
    services:
        - docker:stable-dind
    before_script:
        - apk add --no-cache make
    script:
        - make init
    tags:
        - runner_1