stages:
    - dev

variables:
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_HOST: tcp://docker:2376
    DOCKER_CERT_PATH: "/certs/client"
    DOCKER_TLS_VERIFY: 1
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
cache:
  paths:
    - .cache/pip

before_script:
  - python -V               # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

dev:
    stage: dev
    only:
        - branches
    image: docker/compose:latest
    services:
        - docker:dind
    before_script:
        - apk add --no-cache make
    cache:
        key: ${CI_COMMIT_REF_SLUG}
        paths:
            - frontend/node_modules/
            - cucumber/node_modules/
    script:
        - make init
    after_script:
        - ls -la api/
        - ls -la api/pip_cache
    tags:
        - runner_1