stages:
    - dev

variables:
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_HOST: tcp://docker:2376
    DOCKER_CERT_PATH: "/certs/client"
    DOCKER_TLS_VERIFY: 1

dev:
    stage: dev
    only:
        - branches
    image: docker/compose:latest
    services:
        - docker:stable-dind
    before_script:
        - mount | grep cgroup
        - docker info
        - apk add --no-cache make
    script:
        - make init
    tags:
        - runner_1