stages:
    - dev
    - build

variables:
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_HOST: tcp://docker:2376
    DOCKER_CERT_PATH: "/certs/client"
    DOCKER_TLS_VERIFY: 1
    REGISTRY: ${CI_REGISTRY}/babadook777/more-charts-main
    IMAGE_TAG: ${CI_COMMIT_REF_SLUG}-${CI_PIPELINE_ID}

dev:
    stage: dev
    only:
        - branches
    image: docker/compose:latest
    services:
        - docker:dind
    before_script:
        - apk add --no-cache make
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    cache:
        key: ${CI_COMMIT_REF_SLUG}
        paths:
            - frontend/node_modules/
            - cucumber/node_modules/
    script:
        - make init
        - make push-dev-cache

        - make api-black-check
        - make api-flake8
        - make api-isort

        - make frontend-lintfix
        - make cucumber-lint-fix

        - make api-test
        - make frontend-test
    tags:
        - runner_1
    artifacts:
        paths:
            - api/var/log

build:
    stage: build
    only:
        - branches
    image: docker/compose:latest
    services:
        - docker:dind
    before_script:
        - apk add --no-cache make
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    script:
        - make build
        - make push-build-cache

        - make testing-build
        - make push-testing-build-cache
    tags:
        - runner_1