stages:
    - dev

variables:
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_HOST: tcp://docker:2376
    DOCKER_CERT_PATH: "/certs/client"
    DOCKER_TLS_VERIFY: 1

dev:
    stage: dev
    only:
        - branches
    image: docker/compose:latest
    services:
        - docker:dind
    before_script:
        - apk add --no-cache make
    cache:
        key: ${CI_COMMIT_REF_SLUG}
        paths:
            - api/pip_cache/
            - frontend/node_modules/
            - cucumber/node_modules/
    script:
        - make init
    after_script:
        - ls -la .cache/
        - ls -la .cache/pip
    tags:
        - runner_1